apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-informer
  namespace: kpizza
spec:
  selector:
    matchLabels:
      app: pizza-informer
  replicas: 1
  template:
    metadata:
      labels:
        app: pizza-informer
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: pizza-informer-service-account
      containers:
      - name: pizza-informer
        image: wdalmut/pizza-informer
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
            cpu: "128m"

