apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-pizza-informer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: role-pizza-informer
subjects:
  - kind: ServiceAccount
    name: pizza-informer-service-account
    namespace: kpizza


